[greeter]
background=/usr/share/nikos/wallpaper.png
theme-name=Nordic
icon-theme-name=Papirus-Dark
font-name=JetBrains Mono 11
xft-antialias=true
xft-dpi=96
xft-hintstyle=slight
xft-rgba=rgb
show-clock=true
clock-format=%H:%M — NikOS
position=50%,center 50%,center
