#!/usr/bin/env python3
"""Render the NikOS Plymouth boot chrome from the logo artwork.

Plymouth draws on a bare framebuffer long before any icon theme or font
config exists, so every piece of the splash has to be a pre-rendered PNG
sitting in the theme directory. Xubuntu ships a set of them; NikOS shipped
only the logo, which left the boot with no spinner, no progress bar and, more
importantly, no password prompt on an encrypted disk.

This script renders that set from `assets/plymouth-logo.svg`, so the boot
chrome and the desktop artwork cannot drift apart. Everything it writes is
committed, and the playbook copies the PNGs straight into the theme
directory: the target machine needs no rendering tools at install time.

    python3 scripts/render-plymouth-assets.py

Requires PyGObject with the librsvg pixbuf loader (`gir1.2-rsvg-2.0`,
`librsvg2-common`), which is a development dependency only.
"""

from __future__ import annotations

import math
import re
import sys
import xml.etree.ElementTree as ET
from pathlib import Path

import gi

gi.require_version("GdkPixbuf", "2.0")
from gi.repository import GdkPixbuf  # noqa: E402

REPO_ROOT = Path(__file__).resolve().parent.parent
ASSETS = REPO_ROOT / "assets"
OUT = ASSETS / "plymouth"

# Boot chrome palette. The splash sits on the near-black background set in
# nikos.script, and the mark's blue is the one thing that reads as a colour
# cast on a dim framebuffer, so the whole set is neutral. The ramp keeps the
# logo's hierarchy: what was bright blue stays the brightest element, what was
# muted stays muted.
BRIGHT = "#d8dee9"
MUTED = "#8b949e"
DIM = "#4c566a"
WORDMARK = "#eceff4"

# Colours as they appear in plymouth-logo.svg, mapped onto the ramp above.
LOGO_COLOUR_MAP = {
    "#2196f3": BRIGHT,
    "#90a4ae": MUTED,
    "#eceff4": WORDMARK,
}

SPINNER_FRAMES = 36
SPINNER_SIZE = 96

# The password bullet is a single node lifted off the mark. The whole "N" was
# tried here first and read as literal text: a row of them spells NNNN across
# the dialog rather than masking a passphrase.
BULLET_SIZE = 14

SVG_NS = "{http://www.w3.org/2000/svg}"

PROGRESS_WIDTH = 320
PROGRESS_HEIGHT = 6

DIALOG_WIDTH = 300
DIALOG_HEIGHT = 36

# fsck reuses the progress geometry at a smaller width, as Xubuntu does.
FSCK_WIDTH = 160


def render(svg: str, path: Path, width: int, height: int) -> None:
    loader = GdkPixbuf.PixbufLoader.new_with_type("svg")
    loader.set_size(width, height)
    loader.write(svg.encode("utf-8"))
    loader.close()
    pixbuf = loader.get_pixbuf()
    if pixbuf is None:
        raise RuntimeError(f"librsvg produced no pixbuf for {path.name}")
    path.parent.mkdir(parents=True, exist_ok=True)
    pixbuf.savev(str(path), "png", [], [])


def svg_document(width: int, height: int, body: str) -> str:
    # <svg> first, so gdk-pixbuf can sniff the file. See tests/test_assets.py.
    return (
        '<?xml version="1.0" encoding="UTF-8"?>\n'
        f'<svg xmlns="http://www.w3.org/2000/svg" width="{width}" height="{height}" '
        f'viewBox="0 0 {width} {height}">\n{body}</svg>\n'
    )


def build_mono_logo() -> str:
    """The boot logo, recoloured onto the neutral ramp.

    Derived from plymouth-logo.svg rather than redrawn, so a change to the
    mark reaches the boot splash by re-running this script.
    """
    source = (ASSETS / "plymouth-logo.svg").read_text(encoding="utf-8")

    def swap(match: re.Match[str]) -> str:
        return LOGO_COLOUR_MAP.get(match.group(0).lower(), match.group(0))

    mono = re.sub(r"#[0-9a-fA-F]{6}", swap, source)
    note = (
        "  <!--\n"
        "    Generated by scripts/render-plymouth-assets.py from\n"
        "    plymouth-logo.svg. Edit that file, then re-run the script.\n"
        "  -->\n"
    )
    head, sep, tail = mono.partition(">")
    return head + sep + "\n" + note + tail.lstrip("\n")


def load_mark() -> tuple[list[tuple[float, float, float, float]],
                        list[tuple[float, float, float]], float]:
    """Read the strokes and nodes of the "N" mark out of menu-icon.svg.

    Parsed rather than restated, so the spinner cannot drift away from the
    panel icon. The file is Inkscape output, so it carries sodipodi and
    inkscape elements that are skipped here.
    """
    root = ET.parse(ASSETS / "menu-icon.svg").getroot()
    view = [float(v) for v in root.get("viewBox").split()]
    extent = max(view[2], view[3])

    lines: list[tuple[float, float, float, float]] = []
    nodes: list[tuple[float, float, float]] = []
    for element in root.iter():
        if element.tag == f"{SVG_NS}line":
            lines.append(tuple(float(element.get(a)) for a in ("x1", "y1", "x2", "y2")))
        elif element.tag == f"{SVG_NS}circle":
            nodes.append(tuple(float(element.get(a)) for a in ("cx", "cy", "r")))

    if len(lines) != 3 or len(nodes) != 4:
        raise RuntimeError(
            f"menu-icon.svg: expected 3 strokes and 4 nodes, got {len(lines)} and {len(nodes)}"
        )

    # The strokes are stored in drawing order and chain end to end, which is
    # what lets the highlight run along the mark as one continuous path.
    for first, second in zip(lines, lines[1:]):
        if (first[2], first[3]) != (second[0], second[1]):
            raise RuntimeError("menu-icon.svg: strokes no longer form a single path")

    return lines, nodes, extent


MARK_LINES, MARK_NODES, MARK_EXTENT = load_mark()
MARK_SEGMENTS = [math.dist((x1, y1), (x2, y2)) for x1, y1, x2, y2 in MARK_LINES]
MARK_LENGTH = sum(MARK_SEGMENTS)

# Distance along the path at which each node sits, so a node can brighten as
# the highlight reaches it. Node order in the file is not path order, so each
# one is matched to the vertex it sits on.
MARK_VERTICES = [(MARK_LINES[0][0], MARK_LINES[0][1])] + [
    (x2, y2) for _, _, x2, y2 in MARK_LINES
]
MARK_VERTEX_DISTANCE = [sum(MARK_SEGMENTS[:i]) for i in range(len(MARK_VERTICES))]


def node_distance_along_path(cx: float, cy: float) -> float:
    nearest = min(
        range(len(MARK_VERTICES)),
        key=lambda i: math.dist((cx, cy), MARK_VERTICES[i]),
    )
    return MARK_VERTEX_DISTANCE[nearest]


def build_spinner_frame(frame: int) -> str:
    """One frame of the spinner: a highlight running along the "N" mark.

    The mark is drawn dim, and a short bright dash travels the stroke path
    from the bottom of the left stem, up and across the diagonal, to the top
    of the right stem. Nodes brighten as the dash passes them. Nothing
    rotates, so the figure stays a readable "N" in every frame.
    """
    scale = SPINNER_SIZE / MARK_EXTENT
    stroke = 26.0
    phase = MARK_LENGTH * frame / SPINNER_FRAMES
    dash = MARK_LENGTH * 0.22

    path = f"M {MARK_LINES[0][0]} {MARK_LINES[0][1]} " + " ".join(
        f"L {x2} {y2}" for _, _, x2, y2 in MARK_LINES
    )

    parts = [f'  <g transform="scale({scale:.6f})">\n']
    parts.append(
        f'    <path d="{path}" fill="none" stroke="{DIM}" stroke-width="{stroke}" '
        'stroke-linecap="round" stroke-linejoin="round" opacity="0.55"/>\n'
    )
    # The bright dash wraps at the end of the path, so the loop has no seam.
    for offset in (phase, phase - MARK_LENGTH):
        parts.append(
            f'    <path d="{path}" fill="none" stroke="{BRIGHT}" stroke-width="{stroke}" '
            'stroke-linecap="round" stroke-linejoin="round" '
            f'stroke-dasharray="{dash:.2f} {MARK_LENGTH - dash:.2f}" '
            f'stroke-dashoffset="{-offset:.2f}" opacity="0.9"/>\n'
        )

    for cx, cy, radius in MARK_NODES:
        along = node_distance_along_path(cx, cy)
        delta = abs((along - phase + MARK_LENGTH / 2) % MARK_LENGTH - MARK_LENGTH / 2)
        # Cosine falloff over a quarter of the path, so the glow leads and trails.
        heat = max(0.0, math.cos(min(delta / (MARK_LENGTH / 4), 1.0) * math.pi / 2))
        colour = BRIGHT if heat > 0.5 else MUTED
        parts.append(
            f'    <circle cx="{cx}" cy="{cy}" r="{radius}" fill="{colour}" '
            f'opacity="{0.3 + 0.7 * heat:.3f}"/>\n'
        )

    parts.append("  </g>\n")
    return svg_document(SPINNER_SIZE, SPINNER_SIZE, "".join(parts))


def build_progress_track(width: int) -> str:
    radius = PROGRESS_HEIGHT / 2
    body = (
        f'  <rect x="0" y="0" width="{width}" height="{PROGRESS_HEIGHT}" '
        f'rx="{radius}" ry="{radius}" fill="{DIM}" opacity="0.45"/>\n'
    )
    return svg_document(width, PROGRESS_HEIGHT, body)


def build_progress_fill(width: int) -> str:
    """The bar the script scales horizontally to show progress.

    Kept a flat colour with rounded caps: a gradient would compress along with
    the bar and change hue as the fill grows.
    """
    radius = PROGRESS_HEIGHT / 2
    body = (
        f'  <rect x="0" y="0" width="{width}" height="{PROGRESS_HEIGHT}" '
        f'rx="{radius}" ry="{radius}" fill="{BRIGHT}"/>\n'
    )
    return svg_document(width, PROGRESS_HEIGHT, body)


def build_password_dialog() -> str:
    body = (
        f'  <rect x="0.75" y="0.75" width="{DIALOG_WIDTH - 1.5}" '
        f'height="{DIALOG_HEIGHT - 1.5}" rx="6" ry="6" '
        f'fill="#2e3440" fill-opacity="0.55" stroke="{DIM}" stroke-width="1.5"/>\n'
    )
    return svg_document(DIALOG_WIDTH, DIALOG_HEIGHT, body)


def build_bullet() -> str:
    """Password bullet: one node of the "N" mark, at its own proportions."""
    _, nodes, extent = MARK_LINES, MARK_NODES, MARK_EXTENT
    # Every node carries the same radius, so the first one speaks for the mark.
    node_radius = nodes[0][2]
    centre = BULLET_SIZE / 2
    radius = BULLET_SIZE * (node_radius / extent) * 1.6
    body = (
        f'  <circle cx="{centre}" cy="{centre}" r="{radius:.2f}" fill="{BRIGHT}"/>\n'
    )
    return svg_document(BULLET_SIZE, BULLET_SIZE, body)


def main() -> int:
    OUT.mkdir(parents=True, exist_ok=True)

    mono = build_mono_logo()
    (OUT / "logo-mono.svg").write_text(mono, encoding="utf-8")
    render(mono, OUT / "logo-mono.png", 512, 466)

    for frame in range(SPINNER_FRAMES):
        render(
            build_spinner_frame(frame),
            OUT / f"spinner-{frame + 1:04d}.png",
            SPINNER_SIZE,
            SPINNER_SIZE,
        )

    render(build_progress_track(PROGRESS_WIDTH), OUT / "progress-meter.png",
           PROGRESS_WIDTH, PROGRESS_HEIGHT)
    render(build_progress_fill(PROGRESS_WIDTH), OUT / "progress-fade.png",
           PROGRESS_WIDTH, PROGRESS_HEIGHT)
    render(build_progress_track(FSCK_WIDTH), OUT / "fsck-meter.png",
           FSCK_WIDTH, PROGRESS_HEIGHT)
    render(build_progress_fill(FSCK_WIDTH), OUT / "fsck-fade.png",
           FSCK_WIDTH, PROGRESS_HEIGHT)
    render(build_password_dialog(), OUT / "passw-dialog.png",
           DIALOG_WIDTH, DIALOG_HEIGHT)
    render(build_bullet(), OUT / "bullet.png", BULLET_SIZE, BULLET_SIZE)

    written = sorted(p.name for p in OUT.iterdir())
    print(f"wrote {len(written)} files to {OUT.relative_to(REPO_ROOT)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
